Bytespeicher/Bytebot

- bytebot.py
- bytebot_log.py
- bytebotpluginloader.py
- plugins/autoop.py
- plugins/dates.py
- plugins/ircquestions.py
- plugins/muschi.py
- plugins/penis.py
- plugins/plugin.py
- plugins/rss.py
- plugins/shorturl.py
> Code style enhancements (PEP8, see codacy)

- plugins/parken.py
Dear developers at Bytespeicher,
please add my nice plugin to your Bytebot to view free parking places in Erfurt from IRC.
best regards,
Christoph J.
> adding python plugin for parking places in erfurt

- plugins/dates.py
Attention: new modules used:
- from dateutil.rrule import *
- from dateutil.parser import *
New:
- date command now handles recurrence of events.
- first steps for location handling (yet commented out)
Known issues (rarely used features, however):
- "all day" events not supportet (yet)
- EXDATE in RRULE not supportet (yet)
> added recurrence handling

- plugins/dates.py
No new features added. Just a few comments.
> no new features, just new comments

- plugins/dates.py
Multiline comments are now triple quoted
> multiline comments using triple quotes

- plugins/dates.py
> fixed pep8 conformity

- plugins/spacestatus.py
> Plugin spaceapi - user list

- .travis.yml
> Added Travis flake8 tests

- .travis.yml
- bytebot.py
- bytebot_log.py
- bytebotpluginloader.py
- plugins/autoop.py
- plugins/autotopic.py
- plugins/dates.py
- plugins/ircquestions.py
- plugins/mensa.py
- plugins/messagelogger.py
- plugins/muschi.py
- plugins/parking.py
- plugins/penis.py
- plugins/plugin.py
- plugins/rss.py
- plugins/shorturl.py
> Fix pep8 styles

- plugins/dates.py
> fixed Bug 88

- bytebot_config.py.example
- plugins/fuel.py
Dear devs of the great Bytespeicher,
today i would like to offer a new plug in for bytebot. This plugin will print all fuel prices from stations around the Bytespeicher.
I hope you like it.
Best regards,
Christoph J.
> adding fuel plug in to show fuel prices

- bytebot_config.py.example
- plugins/ccc32c3.py
Dear devs of Bytespeicher,
with this update you can config the events.json file for ccc32c3 plugin with the config.
best regards,
Christoph J.
> adding updates to config path for events.json

- plugins/station.py
Hello, this is a tiny fix for the station plugin
> updating station plugin

- bytebot_config.py.example
- plugins/weather.py
I have created a plugin which shows you the current temperature of Erfurt.
The information is based on the openweathermap API.
> Added weather plugin

- plugins/weather.py
Location function added, now you can search for specific locations.
> extended weather plugin

- bytebot_config.py.example
- contrib/requirements.txt
- plugins/rss.py
* Migrate plugin
* Sync settings from byte_config.py.example with python2 version
> Migrate rss plugin to irc3 (#122)

- plugins/station.py
This plugin uses a new api to get public transportations opportunities.
> rewrite^station plugin with new api

- lib/spaceapi.py
- plugins/status.py
> Refactor for spaceapi library

- plugins/status.py
Removed unused imports, fixed visual indents
> Fixed PEP8 errors

- bytebot_config.py.example
- plugins/wikipedia.py
> Added Bytebot wikipedia plugin

- bytebot_config.py.example
- plugins/parking.py
Hello,
today i created a new parking plugin. Thanks to @suicider for the new parking access link. Feel free to modify the encoding for our special ü. Please also look at #121.
Jurkov
> New parking plugin

- bytebot_config.py.example
- plugins/wikipedia.py
* change keyword from wiki to wikipedia
* add more safety checks
* make length of abstract configurable
> Migrate wikipedia plugin to irc3/python3

- contrib/requirements.txt
- plugins/version.py
...to get running version of the bot from git information
> Version plugin

- plugins/parking.py
* sort car park by name before output
* show vacancy instead of occupancy (API file consists occupancy "belegung")
> Sort by name, fix vacancy (values in api are occupancy)

- plugins/rss.py
> Output error message to log on cron action

- plugins/station.py
> Fix path to data directory.
